<?php
function nasa_wpb_furniture() {
    return array(
        'post' => array(
            'post_content' => '[vc_row fullwidth="1"][vc_column][nasa_pin_products_banner pin_slug="pin-products-home-furniture" bg_icon="#ffffff" txt_color="#333333" border_icon="#fed700"][/vc_column][/vc_row][vc_row el_class="margin-top-60"][vc_column][nasa_title title_text="Featured Categories" title_type="h2" title_bg="#ffffff" title_desc="The freshest and most exciting news" title_align="text-center"][/vc_column][/vc_row][vc_row el_class="desktop-margin-top-30"][vc_column width="1/2"][vc_row_inner][vc_column_inner][nasa_banner valign="bottom" hover="zoom" img_src="3117"]
    <div><a style="background-color: #fff; font-size: 20px; padding: 0 15px;" title="Sofas" href="#"><strong>Sofas</strong></a></div>
    [/nasa_banner][/vc_column_inner][/vc_row_inner][vc_row_inner][vc_column_inner width="1/2"][nasa_banner valign="bottom" hover="zoom" img_src="3115"]
    <div><a style="background-color: #fff; font-size: 20px; padding: 0 15px;" title="Lightning" href="#"><strong>Lightning</strong></a></div>
    [/nasa_banner][/vc_column_inner][vc_column_inner width="1/2"][nasa_banner valign="bottom" hover="fade" img_src="3115"]
    <div><a style="background-color: #fff; font-size: 20px; padding: 0 15px;" title="Clocks" href="#"><strong>Clocks</strong></a></div>
    [/nasa_banner][/vc_column_inner][/vc_row_inner][/vc_column][vc_column width="1/2"][nasa_banner valign="bottom" hover="zoom" img_src="3094"]
    <div><a style="background-color: #fff; font-size: 20px; padding: 0 15px;" title="Chair" href="#"><strong>Chair</strong></a></div>
    [/nasa_banner][/vc_column][/vc_row][vc_row el_class="margin-top-60"][vc_column][nasa_title title_text="Best Seller Product" title_type="h2" title_bg="#ffffff" title_align="text-center"][/vc_column][/vc_row][vc_row][vc_column][vc_tta_tabs alignment="center" tabs_display_type="2d" css=".vc_custom_1550403944446{background-color: #eeee22 !important;}" el_class="nasa-tab-primary-color"][vc_tta_section title="All" tab_id="1550311240722-2cdb1c54-ef96"][nasa_products columns_number="4" columns_number_small="1" columns_number_tablet="2"][/vc_tta_section][vc_tta_section title="Best Seller" tab_id="1550311240736-7586aefb-daf1"][nasa_products type="best_selling" columns_number="4" columns_number_small="1" columns_number_tablet="2"][/vc_tta_section][vc_tta_section title="Featured" tab_id="1550311288684-f7c002b0-60c6"][nasa_products type="featured_product" columns_number="4" columns_number_small="1" columns_number_tablet="2"][/vc_tta_section][vc_tta_section title="On Sale" tab_id="1550311289708-6556397c-37fb"][nasa_products type="on_sale" columns_number="4" columns_number_small="1" columns_number_tablet="2"][/vc_tta_section][vc_tta_section title="Deal" tab_id="1550311290709-86e146eb-efd1"][nasa_products type="deals" columns_number="4" columns_number_small="1" columns_number_tablet="2"][/vc_tta_section][/vc_tta_tabs][/vc_column][/vc_row][vc_row css=".vc_custom_1550418776704{background-color: #fed700 !important;background-position: 0 0 !important;background-repeat: repeat !important;}" el_class="mobile-margin-top-40 mobile-margin-bottom-20 desktop-margin-top-40 desktop-margin-bottom-80 padding-top-15 padding-bottom-15"][vc_column][nasa_slider bullets="false" navigation="false" autoplay="true"][vc_column_text]
    <p class="text-center"><strong>UP TO 70% OFF THE ENTRIRE STORE! - MADE WITH LOVE by <span class="nasa-underline">Nasa studio</span></strong></p>
    [/vc_column_text][vc_column_text]
    <p class="text-center"><strong>UP TO 70% OFF THE ENTRIRE STORE! - MADE WITH LOVE by <span class="nasa-underline">Nasa studio</span></strong></p>
    [/vc_column_text][/nasa_slider][/vc_column][/vc_row][vc_row][vc_column width="1/2" el_class="rtl-right"][vc_video link="https://www.youtube.com/watch?v=DmFtQrnBSe0"][/vc_column][vc_column width="1/2" el_class="desktop-padding-left-40 rtl-right rtl-desktop-padding-left-0 rtl-desktop-padding-right-40"][vc_row_inner][vc_column_inner][nasa_title title_text="About Us" title_type="h2" title_bg="#ffffff"][/vc_column_inner][/vc_row_inner][vc_row_inner][vc_column_inner][vc_column_text]

    Our mission is to bring together a diverse, curated collection of beautiful furniture and homewares from around the world. I was popularised in the 1960s with the release.

    [/vc_column_text][/vc_column_inner][/vc_row_inner][vc_row_inner el_class="margin-top-35"][vc_column_inner width="1/2"][vc_single_image image="2914" el_class="left rtl-right margin-right-20 rtl-margin-left-20 rtl-margin-right-0 margin-top-5"][nasa_title title_text="We work in Global" title_type="h5" title_bg="#ffffff" title_desc="Lorem ipsum" el_class="nasa-clear-none"][/vc_column_inner][vc_column_inner width="1/2"][vc_single_image image="2915" el_class="left rtl-right margin-right-20 rtl-margin-left-20 rtl-margin-right-0 margin-top-5"][nasa_title title_text="Our guarantee" title_type="h5" title_bg="#ffffff" title_desc="From 2 - 5 years" el_class="nasa-clear-none"][/vc_column_inner][/vc_row_inner][vc_row_inner el_class="margin-top-35"][vc_column_inner width="1/2"][vc_single_image image="2916" el_class="left rtl-right margin-right-20 rtl-margin-left-20 rtl-margin-right-0 margin-top-10"][nasa_title title_text="On the market" title_type="h5" title_bg="#ffffff" title_desc="12 years" el_class="nasa-clear-none"][/vc_column_inner][vc_column_inner width="1/2"][vc_single_image image="2917" el_class="left rtl-right margin-right-20 rtl-margin-left-20 rtl-margin-right-0"][nasa_title title_text="Best quality" title_type="h5" title_bg="#ffffff" title_desc="Lorem ipsum" el_class="nasa-clear-none"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row el_class="margin-top-80"][vc_column][nasa_title title_text="Latest Blog" title_type="h2" title_bg="#ffffff" title_desc="The freshest and most exciting news" title_align="text-center"][/vc_column][/vc_row][vc_row][vc_column][nasa_post dots="true" arrows="0" columns_number="3" columns_number_small="1" columns_number_tablet="2" readmore="no" page_blogs="no"][/vc_column][/vc_row][vc_row el_class="margin-top-50"][vc_column width="1/3"][nasa_title title_text="Top Rated" title_type="h4" title_bg="#ffffff"][nasa_products type="top_rate" style="list_carousel" style_row="3" arrows="1" number="6" columns_number="1" columns_number_small="1" columns_number_tablet="2"][/vc_column][vc_column width="1/3"][nasa_title title_text="Best Selling" title_type="h4" title_bg="#ffffff"][nasa_products type="best_selling" style="list_carousel" style_row="3" arrows="1" number="6" columns_number="1" columns_number_small="1" columns_number_tablet="2"][/vc_column][vc_column width="1/3"][nasa_title title_text="On Sale" title_type="h4" title_bg="#ffffff"][nasa_products type="on_sale" style="list_carousel" style_row="3" arrows="1" number="6" columns_number="1" columns_number_small="1" columns_number_tablet="2"][/vc_column][/vc_row][vc_row el_class="margin-top-30 margin-bottom-50"][vc_column][nasa_brands images="3074,3074,3074,3074,3074,3074" columns_number="6" columns_number_tablet="4" columns_number_small="3" is_ajax="no"][/vc_column][/vc_row]',

            'post_title' => 'WPB Furniture',
            'post_name' => 'wpb-furniture'
        ),
        'post_meta' => array(
            '_wpb_shortcodes_custom_css' => '.vc_custom_1550418776704{background-color: #fed700 !important;background-position: 0 0 !important;background-repeat: repeat !important;}.vc_custom_1550403944446{background-color: #eeee22 !important;}'
        )
    );
}
