<?php
function nasa_wpb_fashion_1() {
    return array(
        'post' => array(
            'post_content' => '[vc_row fullwidth="1"][vc_column][rev_slider alias="slider-01-1"][/vc_column][/vc_row][vc_row equal_height="yes" el_class="margin-top-100 nasa-clear-both tablet-margin-top-70 mobile-margin-top-60"][vc_column css_animation="none" width="5/12" width_side="left" css=".vc_custom_1588932392585{background-image: url(https://via.placeholder.com/767x872?text=767x872) !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}"][/vc_column][vc_column css_animation="none" width="7/12" el_class="right desktop-padding-left-20"][nasa_products title_shortcode="For Her" style="carousel" style_row="2" shop_url="0" arrows="1" number="10" columns_number="3" columns_number_small="2" columns_number_tablet="2" cat="woman"][nasa_separator_link title_text="Shop Now" link_text="#" title_type="h5" title_bg="#ffffff" title_hr="full" el_class="margin-bottom-20 mobile-margin-bottom-50"][/vc_column][/vc_row][vc_row el_class="margin-top-100 tablet-margin-top-70 mobile-margin-top-20"][vc_column width="1/2"][nasa_banner height="180px" valign="middle" effect_text="fadeInLeft" hover="zoom" data_delay="500ms" img_src="3098"]
    <h5>Mini backpack</h5>
    <h6 style="color: #999;">Bags &amp; Accessories</h6>
    [/nasa_banner][/vc_column][vc_column width="1/2"][nasa_banner height="180px" valign="middle" text_color="dark" effect_text="fadeInLeft" hover="fade" data_delay="500ms" img_src="3098" link="#"]
    <h5>Big Sale</h5>
    <h3>50% OFF</h3>
    [/nasa_banner][/vc_column][/vc_row][vc_row equal_height="yes" el_class="margin-top-80 tablet-margin-top-50 mobile-margin-top-30"][vc_column width="7/12" el_class="left desktop-padding-right-20"][nasa_products title_shortcode="For Him" style="carousel" style_row="2" title_align="right" shop_url="0" arrows="1" number="12" columns_number="3" columns_number_small="2" columns_number_tablet="2" cat="men"][nasa_separator_link title_text="Shop Now" link_text="#" title_type="h5" title_bg="#ffffff" title_hr="full" title_align="text-right" el_class="margin-bottom-20 mobile-margin-bottom-50"][/vc_column][vc_column css_animation="none" width="5/12" width_side="right" css=".vc_custom_1588932456200{background-image: url(https://via.placeholder.com/767x872?text=767x872) !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}"][/vc_column][/vc_row][vc_row css=".vc_custom_1520435667002{background-color: #f76b6a !important;}" el_class="mobile-margin-top-40 mobile-margin-bottom-20 desktop-margin-top-80 desktop-margin-bottom-80 padding-top-15 padding-bottom-15"][vc_column][nasa_slider bullets="false" navigation="false" autoplay="true"][vc_column_text]
    <p class="color-white text-center" style="letter-spacing: 0.1em; font-weight: bold;">UP TO 70% OFF THE ENTRIRE STORE! - MADE WITH LOVE by <span class="nasa-underline">Nasa studio</span></p>
    [/vc_column_text][vc_column_text]
    <p class="color-white text-center" style="letter-spacing: 0.1em; font-weight: bold;">UP TO 70% OFF THE ENTRIRE STORE! - MADE WITH LOVE by <span class="nasa-underline">Nasa studio</span></p>
    [/vc_column_text][/nasa_slider][/vc_column][/vc_row][vc_row][vc_column width="1/3"][nasa_title title_text="Top Rated" title_type="h4" title_bg="#ffffff" el_class="margin-bottom-20"][nasa_products type="top_rate" style="list_carousel" style_row="3" arrows="1" number="6" columns_number="1" columns_number_small="1" columns_number_tablet="1"][/vc_column][vc_column width="1/3"][nasa_title title_text="Best Selling" title_type="h4" title_bg="#ffffff" el_class="margin-bottom-20"][nasa_products type="best_selling" style="list_carousel" style_row="3" arrows="1" number="6" columns_number="1" columns_number_small="1" columns_number_tablet="1"][/vc_column][vc_column width="1/3"][nasa_title title_text="Recent" title_type="h4" title_bg="#ffffff" el_class="margin-bottom-20"][nasa_products style="list_carousel" style_row="3" arrows="1" number="6" columns_number="1" columns_number_small="1" columns_number_tablet="1"][/vc_column][/vc_row][vc_row el_class="padding-top-50 margin-bottom-50"][vc_column][nasa_brands images="3074,3074,3074,3074,3074,3074" columns_number="6" columns_number_tablet="4" columns_number_small="3" custom_links="#,#,#,#,#,#"][/vc_column][/vc_row]',
            'post_title' => 'WPB Fashion 1',
            'post_name' => 'wpb-fashion-1'
        ),
        'post_meta' => array(
            '_nasa_header_block' => 'static-header-1',
            '_nasa_el_class_header' => 'main-home-fix',
            '_wpb_shortcodes_custom_css' => '.vc_custom_1520435667002{background-color: #f76b6a !important;}.vc_custom_1588932392585{background-image: url(https://via.placeholder.com/767x872?text=767x872) !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}.vc_custom_1588932456200{background-image: url(https://via.placeholder.com/767x872?text=767x872) !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}'
        )
    );
}
